include:
#  - blackhole/docker-compose.yml
#  - zurg/docker-compose.yml
  - compose/bazarr.yml
  # - compose/cross-seed.yml
  # - compose/meilisearch.yml
  - compose/gotify.yml
  - compose/jellyfin.yml
  - compose/jellyseerr.yml
  # - compose/jellystat.yml
  - compose/jfa-go.yml
  - compose/prowlarr.yml
  # - compose/gluetun.yml
  #  - compose/qbitmanage.yml
  - compose/qbittorrent.yml
  - compose/qui.yml

  - compose/radarr.yml
  - compose/sonarr.yml
  - compose/kapowarr.yml
  # - compose/mylar3.yml
  # - compose/lidarr.yml
  # - compose/readarr.yml

  # - compose/autobrr.yml
  - compose/byparr.yml
  - compose/landing.yml
  - compose/flaresolverr.yml
  # - compose/calibre.yml
  # - compose/plex.yml
  # - compose/jellyplex-watched.yml

  # Homarr - Dashboard
  # - compose/homarr.yml

  # Dash - Monitor Resources
  # - compose/dash.yml

  # Gameyfin - Video Game Library Manager
  # - compose/gameyfin.yml

  # Tracearr
  - compose/tracearr.yml

  # Swiparr
  # - compose/swiparr.yml

  # TubeArchivist
  # - compose/tubearchivist.yml

  # Dozzle - Docker Logs Viewer
  - compose/dozzle.yml

networks:
  traefik-net:
  qbit-net:
