include:
  - compose/landing.yml

  # Downloaders
  - blackhole/docker-compose.yml
  - zurg/docker-compose.yml
  - compose/qui.yml
  - compose/qbittorrent.yml

  # Jellyfin Stack
  - compose/jellyfin.yml
  - compose/jellyseerr.yml
  - compose/jfa-go.yml

  # Arr* Applications
  - compose/prowlarr.yml
  - compose/radarr.yml
  - compose/sonarr.yml
  - compose/byparr.yml
  - compose/bazarr.yml

  # Gotify - Notifications
  - compose/gotify.yml

  # Homarr - Dashboard
  # - compose/homarr.yml

  # Dash - Monitor Resources
  # - compose/dash.yml

  # Gameyfin - Video Game Library Manager
  # - compose/gameyfin.yml

  # Tracearr
  - compose/tracearr.yml

  # Swiparr
  # - compose/swiparr.yml

  # TubeArchivist
  # - compose/tubearchivist.yml

  # Dozzle - Docker Logs Viewer
  - compose/dozzle.yml

networks:
  traefik-net:
  qbit-net:
