include:
  - blackhole/docker-compose.yml
  - compose/bazarr.yml
  - compose/flaresolverr.yml
  - compose/gotify.yml
  - compose/homarr.yml
  - compose/jellyfin.yml
  - compose/jellyplex-watched.yml
  - compose/jellyseerr.yml
  - compose/jellystat.yml
  - compose/jfa-go.yml
  - compose/kuma.yml
  - compose/plex.yml
  - compose/plexautolanguage.yml
  - compose/prowlarr.yml
  - compose/qbitmanage.yml
  - compose/qbittorrent.yml
  - compose/radarr.yml
  - compose/rflood.yml
  - compose/socket-proxy.yml
  - compose/sonarr.yml
  - compose/tautulli.yml
  - compose/unmanic.yml
  - compose/wizarr.yml
  - compose/traefik.yml
  - compose/vaultwarden.yml
  - compose/grafana.yml
  # - varken/compose.yml
  - zurg/docker-compose.yml

networks:
  traefik-net:
      ipam:
      config:
        - subnet: "192.168.7.0/24"
  socket-proxy:
  qbit-net: