version: "3.8"
services:

  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v1.5.3
    container_name: sonarr-exporter
    command: ["sonarr"]
    environment:
      PORT: 9707
      URL: ${SONARR_ADDRESS}
      APIKEY: ${SONARR_API_KEY}
    #    networks:
    #    - your_custom_network # optional
    ports:
    - "9707:9707"
    restart: unless-stopped

  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v1.5.3
    container_name: radarr-exporter
    command: ["radarr"]
    environment:
      PORT: 9708
      URL: ${RADARR_ADDRESS}
      APIKEY: ${RADARR_API_KEY}
    #    networks:
    #    - your_custom_network # optional
    ports:
    - "9708:9708"
    restart: unless-stopped

  # lidarr-exporter:
  #   image: ghcr.io/onedr0p/exportarr:v1.5.3
  #   container_name: lidarr-exporter
  #   command: ["lidarr"]
  #   environment:
  #     PORT: 9709
  #     URL: ${LIDARR_ADDRESS}
  #     APIKEY: ${LIDARR_API_KEY}
  #   #    networks:
  #   #     - your_custom_network # optional
  #   ports:
  #   - "9709:9709"
  #   restart: unless-stopped

  prowlarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v1.5.3
    container_name: prowlarr-exporter
    command: ["prowlarr"]
    environment:
      PORT: 9710
      URL: ${PROWLARR_ADDRESS}
      APIKEY: ${PROWLARR_API_KEY}
      # PROWLARR_BACKFILL: true # optional
    # PROWLARR_BACKFILL_SINCE_DATE: "2023-03-01" # optional
    #    networks:
    #     - your_custom_network # optional
    ports:
    - "9710:9710"
    restart: unless-stopped

  # sabnzbd-exporter:
  #   image: ghcr.io/onedr0p/exportarr:v1.5.3
  #   container_name: sabnzbd-exporter
  #   command: ["sabnzbd"]
  #   environment:
  #     PORT: 9711
  #     URL: "${SONARR_ADDRSS}}}
  #     APIKEY: ${SONARR_API_KEY}
  #   #    networks:
  #   #     - your_custom_network # optional
  #   ports:
  #   - "9711:9711"
  #   restart: unless-stopped