services:
  bazarr:
    container_name: bazarr
    restart: unless-stopped
    image: ghcr.io/hotio/bazarr
    ports:
    - "6767:6767"
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK=${UMASK}
    - TZ=${TZ}
    - WEBUI_PORTS=6767/tcp,6767/udp
    volumes:
    - ${APPDATA_PATH}/bazarr:/config
    - ${DATA_PATH}:/data
    - /mnt:/mnt
    depends_on:
      rclone:
        condition: service_healthy
        restart: true
    networks:
    - traefik-net
    labels:
    - "org.hotio.pullio.notify=true"
    - "org.hotio.pullio.update=true"
    - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
    - "traefik.enable=true"
    - "traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN}`)"
    - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
    # - "traefik.http.routers.bazarr.middlewares=noindex@file,redirect-to-https@file"
    # - "traefik.http.routers.bazarr.tls.certresolver=myresolver"
    # - "traefik.http.routers.bazarr-redirect.rule=Host(`bazarr.${DOMAIN}`)"
    # - "traefik.http.routers.bazarr-redirect.entrypoints=web"
