services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: 21hsmw/flaresolverr:nodriver
    container_name: flaresolverr
    restart: unless-stopped
    environment:
    - LOG_LEVEL=${LOG_LEVEL:-info}
    - LOG_HTML=${LOG_HTML:-false}
    - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    - TZ=${TZ}
    ports:
    - "${PORT:-8191}:8191"
