services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    profiles: [ monitor, all ]
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    networks:
    - traefik-net
    volumes:
    - ${APPDATA_PATH}/grafana:/var/lib/grafana
    - ${APPDATA_PATH}/grafana/dashboards:/var/lib/grafana/dashboards
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.grafana.rule=Host(`grafana.lan`)"
    - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
    - ${APPDATA_PATH}/prometheus/config:/etc/prometheus/
    - ${APPDATA_PATH}/prometheus/data:/prometheus
    - ./build/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./build/prometheus/alert.rules:/etc/prometheus/alert.rules
    profiles: [ monitor, all ]
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
    - 9090:9090
    # links:
    # - cadvisor:cadvisor
    # - alertmanager:alertmanager
    networks:
    - traefik-net
    user: root
    restart: always
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.prometheus.rule=Host(`prometheus.lan`)"
    - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
