#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${APPDATA_PATH}/homarr:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=7e3e38f1be189227eb19f396912ba9da31a97de67490f79093a3f6359891c5bc
    networks:
      - traefik-net
    ports:
      - '7575:7575'
