services:
  jellyfin:
    # container_name: jellyfin
    restart: unless-stopped
    # image: ghcr.io/hotio/jellyfin
    build:
      context: ./build/jellyfin
      dockerfile: Dockerfile.jellyfin
    # ports:
    # - "8096:8096"
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK=${UMASK}
    - TZ=${TZ}
    volumes:
    - ${APPDATA_PATH}/jellyfin:/config
    - ${DATA_PATH}:/data
    - ${APPDATA_PATH}/jellyfin/featured-content/List.txt:/usr/share/jellyfin/web/ui/List.txt
    - /mnt:/mnt
    ports:
    - 8096:8096
    healthcheck:
      test: curl -f localhost:8096/web/index.html || exit 1
      interval: 1m
      timeout: 10s
      retries: 5
    depends_on:
      rclone:
        condition: service_healthy
        restart: true
    networks:
    - traefik-net
    labels:
    - "org.hotio.pullio.notify=true"
    - "org.hotio.pullio.update=true"
    - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
    - "traefik.enable=true"
    - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.lan`)"
    - "traefik.http.services.jellyfin.loadbalancer.server.port=8096" # Default Jellyfin port
    - "traefik.http.routers.jellyfin.middlewares=noindex@file"
    - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
    - "traefik.http.routers.jellyfin-redirect.rule=Host(`jellyfin.lan`)"
    - "traefik.http.routers.jellyfin-redirect.entrypoints=web"
    - "traefik.http.routers.jellyfin-redirect.middlewares=redirect-to-https@file"
    # deploy:
    #   mode: replicated
    #   replicas: 3
    #   restart_policy:
    #     condition: on-failure
    #     delay: 5s
    #     max_attempts: 3
    #     window: 120s
    #   update_config:
    #     parallelism: 1
    #     delay: 10s
    #     order: start-first
    #     failure_action: rollback
    #     monitor: 1m
    #     max_failure_ratio: 0.3

  jellyfin_exporter:
    image: rebelcore/jellyfin-exporter:v1.3.2
    container_name: jellyfin_exporter
    profiles: [ monitor, all ]
    command:
    - '--jellyfin.address=http://jellyfin:8096'
    - '--jellyfin.token=${JELLYFIN_TOKEN}'
    ports:
    - 9594:9594
    networks:
    - traefik-net
    restart: unless-stopped
