services:
  jellystat-db:
    image: postgres:15.2
    environment:
      POSTGRES_DB: 'jfstat'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    networks:
    - traefik-net
    volumes:
    - jellystat-db:/var/lib/postgresql/data # Mounting the volume

  jellystat:
    image: cyfershepard/jellystat:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'my-secret-jwt-key'
    ports:
    - "8097:3000" #Server Port
    volumes:
    - jellystat:/app/backend/backup-data # Mounting the volume
    depends_on:
    - jellystat-db
    restart: unless-stopped
    networks:
    - traefik-net
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.jellystat.rule=Host(`jellystat.${DOMAIN}`)"
    - "traefik.http.services.jellystat.loadbalancer.server.port=3000"
    # - "traefik.http.routers.jellystat.middlewares=noindex@file,redirect-to-https@file"
    # - "traefik.http.routers.jellystat.tls.certresolver=myresolver"
    # - "traefik.http.routers.jellystat-redirect.rule=Host(`jellystat.${DOMAIN}`)"
    # - "traefik.http.routers.jellystat-redirect.entrypoints=web"

volumes:
  jellystat:
  jellystat-db:
