services:
  jfa-go:
    container_name: jfa-go
    image: hrfee/jfa-go
    ports:
    - 8056:8056
    volumes:
    - ${APPDATA_PATH}/jfa-go:/data
    - ${APPDATA_PATH}/jellyfin:/jf
    - /etc/localtime:/etc/localtime:ro
    networks:
    - traefik-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8056"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      jellyfin:
        condition: service_healthy
        restart: true
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.jfa-go.rule=Host(`jfa-go.${DOMAIN}`)"
    - "traefik.http.services.jfa-go.loadbalancer.server.port=8056"
    # - "traefik.http.routers.jfa-go.middlewares=noindex@file,redirect-to-https@file"
    # - "traefik.http.routers.jfa-go.tls.certresolver=myresolver"
    # - "traefik.http.routers.jfa-go-redirect.rule=Host(`jfa-go.${DOMAIN}`)"
    # - "traefik.http.routers.jfa-go-redirect.entrypoints=web"
