services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
    - ./data:/app/data
    ports:
    - 3001:3001
    restart: unless-stopped
    networks:
    - traefik-net
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.uptime-kuma.rule=Host(`kuma.lan`)"
    - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
    - "traefik.http.routers.uptime-kuma.middlewares=noindex@file,redirect-to-https@file"
    - "traefik.http.routers.uptime-kuma.tls.certresolver=myresolver"
    - "traefik.http.routers.uptime-kuma-redirect.rule=Host(`kuma.lan`)"
    - "traefik.http.routers.uptime-kuma-redirect.entrypoints=web"
