services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
    - ${APPDATA_PATH}/uptime-kuma/data:/app/data
    ports:
    - 3002:3001
    restart: unless-stopped
    networks:
    - socket-proxy
    - traefik-net
    environment:
    - DOCKER_HOST=tcp://socket-proxy:2375
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3001" ]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.uptime-kuma.rule=Host(`status.${DOMAIN}`)"
    - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
    # - "traefik.http.routers.uptime-kuma.middlewares=noindex@file,redirect-to-https@file"
    # - "traefik.http.routers.uptime-kuma.tls.certresolver=myresolver"
    # - "traefik.http.routers.uptime-kuma-redirect.rule=Host(`kuma.${DOMAIN}`)"
    # - "traefik.http.routers.uptime-kuma-redirect.entrypoints=web"
