services:
  plexautolanguages:
    image: remirigal/plex-auto-languages:latest
    restart: unless-stopped
    environment:
    #- PLEX_URL=https://plex.antxis.fr
    #- PLEX_TOKEN=${PLEX_TOKEN}
    - TZ=${TZ}
    volumes:
    - ${APPDATA_PATH}/plexautolanguages:/config
    depends_on:
      plex:
        condition: service_healthy
        restart: true
    labels:
    - "org.hotio.pullio.notify=true"
    - "org.hotio.pullio.update=true"
    - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
