services:
  qbitmanage:
    container_name: qbitmanage
    image: ghcr.io/hotio/qbitmanage
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK=${UMASK}
    - TZ=${TZ}
    depends_on:
      qbittorrent:
        condition: service_healthy
        restart: true
    networks:
      - qbit-net
    volumes:
    - ${APPDATA_PATH}/qbitmanage:/config
    - ${APPDATA_PATH}/qbittorrent:/qbittorrent
    - ${DATA_PATH}:/data
