services:
  qbittorrent:
    container_name: qbittorrent
    restart: unless-stopped
    image: hotio/qbittorrent:release-4.5.5
    ports:
    - "8080:8080"
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK=${UMASK}
    - TZ=${TZ}
    - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
    - ${APPDATA_PATH}/qbittorrent:/config
    - ${DATA_PATH}:/data
    labels:
    - "org.hotio.pullio.notify=true"
    - "org.hotio.pullio.update=false"
    - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
    - "traefik.enable=true"
    - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.lan`)"
    - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080" # Default qBittorrent port
    networks:
    - traefik-net
