services:
  radarr:
    container_name: radarr
    restart: unless-stopped
    image: ghcr.io/hotio/radarr
    ports:
    - "7878:7878"
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK=${UMASK}
    - TZ=${TZ}
    networks:
    - traefik-net
    volumes:
    - ${APPDATA_PATH}/radarr:/config
    - ${DATA_PATH}:/data
    - /mnt:/mnt
    depends_on:
    - rclone
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    labels:
    - "org.hotio.pullio.notify=true"
    - "org.hotio.pullio.update=true"
    - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
    - "traefik.enable=true"
    - "traefik.http.routers.radarr.rule=Host(`radarr.lan`)"
    - "traefik.http.services.radarr.loadbalancer.server.port=7878" # Default Jellyfin port
    - "traefik.http.routers.radarr.middlewares=noindex@file"
    - "traefik.http.routers.radarr.tls.certresolver=myresolver"
    - "traefik.http.routers.radarr-redirect.rule=Host(`radarr.lan`)"
    - "traefik.http.routers.radarr-redirect.entrypoints=web"
    - "traefik.http.routers.radarr-redirect.middlewares=redirect-to-https@file"
