services:
  tautulli:
    container_name: tautulli
    image: ghcr.io/hotio/tautulli
    ports:
    - "8181:8181"
    environment:
    - PUID=1000
    - PGID=1000
    - UMASK=002
    - TZ=Etc/UTC
    - WEBUI_PORTS=8181/tcp,8181/udp
    volumes:
    - ${APPDATA_PATH}/tautulli:/config
    networks:
    - traefik-net
    labels:
    - "org.hotio.pullio.notify=true"
    - "org.hotio.pullio.update=true"
    - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
    - "traefik.enable=true"
    - "traefik.http.routers.tautulli.rule=Host(`tautulli.${DOMAIN}`)"
    - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
    - "traefik.http.routers.tautulli.middlewares=noindex@file,redirect-to-https@file"
    - "traefik.http.routers.tautulli.tls.certresolver=myresolver"
    - "traefik.http.routers.tautulli-redirect.rule=Host(`tautulli.${DOMAIN}`)"
    - "traefik.http.routers.tautulli-redirect.entrypoints=web"
