services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
    - "--configFile=/etc/traefik/traefik.yml"
    ports:
    - "80:80" # HTTP
    - "443:443" # HTTPS
    - "8087:8080" # Traefik dashboard
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro # Allow Traefik to access Docker
    - ./config/traefik.yml:/etc/traefik/traefik.yml # Configurations
    - ${APPDATA_PATH}/traefik:/etc/traefik/letsencrypt # Configurations
    networks:
    - traefik-net
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.traefik.rule=Host(`traefik.lan`)" # Route for Traefik
    - "traefik.http.services.traefik.loadbalancer.server.port=8080" # Dashboard port
    - 'traefik.http.middlewares.auth.basicauth.users=admin:$apr1$cktgRUyh$Mdg4SnDK8WBqt9ObfwQpm.' # Optional: Basic auth for security
