services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
    - "--configFile=/etc/traefik/traefik.yml"
    ports:
    - "80:80" # HTTP
    - "443:443" # HTTPS
    environment:
    - DOCKER_HOST=tcp://socket-proxy:2375
    volumes:
    # - /var/run/docker.sock:/var/run/docker.sock:ro # Allow Traefik to access Docker
    - ./config/traefik.yml:/etc/traefik/traefik.yml # Configurations
    - ${APPDATA_PATH}/traefik:/etc/traefik/letsencrypt # Configurations
    networks:
    - traefik-net
    - socket-proxy
    depends_on:
    - socket-proxy
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.traefik.rule=Host(`traefik.lan`)" # Route for Traefik
    - "traefik.http.services.traefik.loadbalancer.server.port=8080" # Dashboard port
    - 'traefik.http.middlewares.auth.basicauth.users=admin:$apr1$cktgRUyh$Mdg4SnDK8WBqt9ObfwQpm.' # Optional: Basic auth for security
