services:
  unmanic:
    container_name: unmanic
    restart: unless-stopped
    image: josh5/unmanic:latest
    ports:
    - 8888:8888
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    volumes:
    - ${APPDATA_PATH}/unmanic:/config
    - ${DATA_PATH}/media:/library
    - /tmp/unmanic:/tmp/unmanic
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.unmanic.rule=Host(`unmanic.${DOMAIN}`)"
    - "traefik.http.services.unmanic.loadbalancer.server.port=8888"
    # - "traefik.http.routers.unmanic.middlewares=noindex@file,redirect-to-https@file"
    # - "traefik.http.routers.unmanic.tls.certresolver=myresolver"
    # - "traefik.http.routers.unmanic-redirect.rule=Host(`unmanic.${DOMAIN}`)"
    # - "traefik.http.routers.unmanic-redirect.entrypoints=web"
